-- AlterTable
ALTER TABLE `notifications` MODIFY `tipo` ENUM('SOLICITUD_AMISTAD', 'AMISTAD_ACEPTADA', 'LIKE_POST', 'COMENTARIO_POST', 'POST_COMPARTIDO', 'MENSAJE_NUEVO', 'VISITA_PERFIL', 'MENCION') NOT NULL;
